version: "3.9"

services:
  nuclio:
    image: nuclio/dashboard:stable-amd64
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    ports:
      - "8070:8070"

  redis:
    image: redis:6.2.3-alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: cyrilix/rabbitmq-mqtt
    ports:
      - "9000:15672"
      - "1883:1883"
      - "5672:5672"
      - "15675:15675"
