apiVersion: "nuclio.io/v1"
kind: Function
metadata:
  name: light-on-control
  namespace: nuclio
spec:
  handler: "main:handler"
  description: "This function runs every minute, checks if there are any lights on for more than two minutes and if so, sends a message on the iot/lightsWarning topic."
  runtime: nodejs
  image: "nuclio/light-on-control:latest"
  minReplicas: 1
  maxReplicas: 1
  targetCPU: 75
  triggers:
    rangeTimeTrigger:
      kind: cron
      attributes:
        interval: 1m
  build:
    functionSourceCode: Y29uc3QgcmVkaXMgPSByZXF1aXJlKCJyZWRpcyIpOwpjb25zdCBtcXR0ID0gcmVxdWlyZSgibXF0dCIpOwpjb25zdCB1cmwgPSByZXF1aXJlKCJ1cmwiKTsKY29uc3QgeyBwcm9taXNpZnkgfSA9IHJlcXVpcmUoInV0aWwiKTsKCmNvbnN0IG1xdHRfdXJsID0gdXJsLnBhcnNlKAogIHByb2Nlc3MuZW52LkNMT1VEQU1RUF9NUVRUX1VSTCB8fCAibXF0dDovL2d1ZXN0Omd1ZXN0QHJhYmJpdG1xOjE4ODMiCik7CmNvbnN0IGF1dGggPSAobXF0dF91cmwuYXV0aCB8fCAiOiIpLnNwbGl0KCI6Iik7CmNvbnN0IG5ld1VybCA9ICJtcXR0Oi8vIiArIG1xdHRfdXJsLmhvc3Q7Cgp2YXIgb3B0aW9ucyA9IHsKICBwb3J0OiBtcXR0X3VybC5wb3J0LAogIGNsaWVudElkOiAibXF0dGpzXyIgKyBNYXRoLnJhbmRvbSgpLnRvU3RyaW5nKDE2KS5zdWJzdHIoMiwgOCksCiAgdXNlcm5hbWU6IGF1dGhbMF0sCiAgcGFzc3dvcmQ6IGF1dGhbMV0sCn07CgpleHBvcnRzLmhhbmRsZXIgPSBmdW5jdGlvbiAoY29udGV4dCwgZXZlbnQpIHsKICBjb25zdCBtcXR0Q2xpZW50ID0gbXF0dC5jb25uZWN0KG5ld1VybCwgb3B0aW9ucyk7CiAgY29uc3QgcmVkaXNDbGllbnQgPSByZWRpcy5jcmVhdGVDbGllbnQoeyBob3N0OiAicmVkaXMiIH0pOwogIGNvbnN0IGdldEFzeW5jID0gcHJvbWlzaWZ5KHJlZGlzQ2xpZW50LmdldCkuYmluZChyZWRpc0NsaWVudCk7CgogIG1xdHRDbGllbnQub24oImNvbm5lY3QiLCAoKSA9PiB7CiAgICByZWRpc0NsaWVudC5rZXlzKCIqIiwgKGVyciwga2V5cykgPT4gewogICAgICBpZiAoZXJyKSBjb250ZXh0LmNhbGxiYWNrKCJFUlJPUiIpOwogICAgICBpZiAoa2V5cy5sZW5ndGggPT09IDApIHsKICAgICAgICBtcXR0Q2xpZW50LmVuZCgpOwogICAgICAgIGNvbnRleHQuY2FsbGJhY2soIk5vIGxpZ2h0IG9uIik7CiAgICAgIH0KICAgICAga2V5cy5mb3JFYWNoKGFzeW5jIChrZXksIGksIGFycikgPT4gewogICAgICAgIGNvbnN0IGxpZ2h0RGF0ZSA9IGF3YWl0IGdldEFzeW5jKGtleSk7CiAgICAgICAgY29uc3QgZGlmZmVyZW5jZSA9IChuZXcgRGF0ZSgpIC0gbmV3IERhdGUobGlnaHREYXRlKSkgLyAxMDAwIC8gNjA7CiAgICAgICAgaWYgKGRpZmZlcmVuY2UgPj0gMikgewogICAgICAgICAgbXF0dENsaWVudC5wdWJsaXNoKCJpb3QvbGlnaHRzV2FybmluZyIsIGtleSwgKCkgPT4gewogICAgICAgICAgICBpZiAoYXJyLmxlbmd0aCAtIDEgPT09IGkpIHsKICAgICAgICAgICAgICBtcXR0Q2xpZW50LmVuZCgpOwogICAgICAgICAgICB9CiAgICAgICAgICB9KTsKICAgICAgICB9CiAgICAgIH0pOwogICAgICBjb250ZXh0LmNhbGxiYWNrKCJOb3RpZmljYXRpb25zIHNlbnQhIik7CiAgICB9KTsKICB9KTsKCiAgLy8gY2xpZW50LnF1aXQoKTsKfTsK
    commands:
      - 'npm install redis'
      - 'npm install mqtt'
    codeEntryType: sourceCode
  platform:
    attributes:
      network: lightson_default
